<?php


class HouseSummary {
	private $status;//在售状态,
	private $weight;//权重,
	private $price_total_rmb; //人民币,
	private $is_online;//上下线状态,
	private $promotion_img;//推广图,
	private $banner_infos;//Banner图,
	private $room_name;//房产标题,
	private $room_desc;//房产描述,
	private $room_country;//国家,
	private $room_city;//城市,
	private $room_zone;//区域,
	private $base_info_tags;//基础信息标签,
	private $room_rate;//近一年房价涨幅,
	private $rental_rate;//年均租金
	private $downpayment_rate;//首付款比率,
	private $loan_payments_rate;//贷款首付比率,
	private $currency_gb;//币种,
	private $room_price_total;//外币最低总价,
	private $apartment_type;//物业类型,
	private $invest_purpose;//投资目的,
	private $property_right;//产权年限,
	private $price_per_sqm;//项目均价,
	private $room_area_min;//最小使用面积,
	private $room_area_max;//最大使用面积,
	private $room_standard;//交房标准,
	private $handing_in_date;//交房时间,
	private $house_info_tags;//房源信息选填标签,
	private $house_layout_infos;//户型,
	private $house_longitude;//经度,
	private $house_latitude;//纬度,
	private $house_static_map;//静态位置地图,
	private $location_round;//位置周边,
	private $purchase_process;//购房流程,
	private $full_trading_period;//全款交易阶段,
	private $full_holding_period;//全款持有阶段,
	private $loan_trading_period;//贷款交易阶段,
	private $loan_holding_period;//贷款持有阶段,
	private $loan_rate_max;//贷款最高比例,
	private $loan_year_limit;//贷款最高年限,
	private $loan_annual_rate;//贷款年利率,
	private $project_intro;//项目介绍,
	private $join_assess;//不参与评估选,
	private $annual_net_earnings_rate;//年均净收益,
	private $promotion_video;//推广视频,
	private $video_pro;//视频介绍,
	private $vr_link;//VR链接,
	private $code_img;//小程序二维码图片,
	private $national_short_en;//国家缩写,
	private $national_city_short_en;//城市缩写,
	private $city_id;//城市ID,
	private $national_name;//国家名,
	private $process_id;//业务流程,
	private $project_leader;//项目方,
	private $project_news;//项目动态,
	private $payment_deposit;//意向金

}